/**
 * phant-stream-csv
 * https://github.com/sparkfun/phant-stream-csv
 *
 * Copyright (c) 2014 SparkFun Electronics
 * Licensed under the GPL v3 license.
 */

'use strict';

/**** Module dependencies ****/
var stream = require('stream'),
    util = require('util');

/**** Make Readable a readable stream ****/
util.inherits(Readable, stream.Readable);

/**** Readable prototype ****/
var app = Readable.prototype;

/**** Expose Readable ****/
exports = module.exports = Readable;

/**** Initialize a new Readable ****/
function Readable(id, options) {

  if (! (this instanceof Readable)) {
    return new Readable(id, options);
  }

  options = util._extend({
    highWaterMark: 64 * 1024 // 64k
  }, options || {});

  stream.Readable.call(this);

  // id generated by metadata module
  this.id = id;

  // apply the options
  util._extend(this, options || {});

}

app.page = 1;
app.all = false;

