/**
 * phant-stream-csv
 * https://github.com/sparkfun/phant-stream-csv
 *
 * Copyright (c) 2014 SparkFun Electronics
 * Licensed under the GPL v3 license.
 */

'use strict';

/**** Module dependencies ****/
var stream = require('stream'),
    util = require('util');

/**** Make Writable a writable stream ****/
util.inherits(Writable, stream.Writable);

/**** Writable prototype ****/
var app = Writable.prototype;

/**** Expose Writable ****/
exports = module.exports = Writable;

/**** Initialize a new Writable ****/
function Writable(id, options) {

  if (! (this instanceof Writable)) {
    return new Writable(id, options);
  }

  stream.Writable.call(this);

  // id generated by metadata module
  this.id = id;

  // apply the options
  util._extend(this, options || {});

}

app.cap = 50 * 1024 * 1024; // 50mb limit for streams
app.chunk = 500 * 1024; // 500k chunks
